#!/usr/bin/env php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Minicli\App;
use Minicli\Exception\CommandNotFoundException;
use Twig\Environment;
use Twig\Loader\FilesystemLoader;

$app = new App([
    'app_path' => [
        __DIR__ . '/app/Command',
        '@minicli/command-help'
    ],
    'debug' => true
]);

$loader = new FilesystemLoader(__DIR__ . '/app/Views');
$twig = new Environment($loader, [
    'cache' => __DIR__ . '/app/Views/cache',
]);

if (! function_exists('view')) {
    function view(string $template, array $data = []): string
    {
        global $twig;
        return $twig->render($template, $data);
    }
}

try {
    $app->runCommand($argv);
} catch (CommandNotFoundException $notFoundException) {
    $app->getPrinter()->error("Command Not Found.");
    return 1;
} catch (Exception $exception) {
    if ($app->config->debug) {
        $app->getPrinter()->error("An error occurred:");
        $app->getPrinter()->error($exception->getMessage());
    }
    return 1;
}

return 0;
