#!/usr/bin/env php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use App\Services\TermwindOutputHandler;
use App\Services\TermwindService;
use App\Services\TwigService;
use Minicli\App;
use Minicli\Exception\CommandNotFoundException;

$app = new App([
    'app_path' => [
        __DIR__ . '/app/Command',
        '@minicli/command-help'
    ],
    'debug' => true
]);

// Register Termwind Service
$app->addService('termwind', new TermwindService());

// Register Twig Service
$app->addService('twig', new TwigService());

// Register Termwind Output Handler
$app->setOutputHandler(new TermwindOutputHandler());

try {
    $app->runCommand($argv);
} catch (CommandNotFoundException $notFoundException) {
    $app->getPrinter()->error("Command Not Found.");
    return 1;
} catch (Exception $exception) {
    if ($app->config->debug) {
        $app->getPrinter()->error("An error occurred:");
        $app->getPrinter()->error($exception->getMessage());
    }
    return 1;
}

return 0;
